TargetIntensity: 50000
MinIntTime: 50
MaxIntTime: 300
IntTimeStep: 10
GPSCOMPort: 0
FitWindow:
  - 310
  - 320
FRSPath: /home/pi/PiSpec/Ref/sao2010.txt
FitParameters:
  SO2:
    value: 1.0e16
    vary: True
    xpath: /home/pi/PiSpec/Ref/SO2_295K.txt
  O3:
    value: 1.0e19
    vary: True
    xpath: /home/pi/PiSpec/Ref/O3_Voigt_223K.txt
  Ring:
    value: 0.1
    vary: True
    xpath: /home/pi/PiSpec/Ref/Ring.txt
  bg_poly0:
    value: 0.0
  bg_poly1:
    value: 0.0
  bg_poly2:
    value: 0.0
  bg_poly3:
    value: 1.0
  shift0:
    value: 0.0
    vary: True
  shift1:
    value: 0.1
    vary: True
  fwem:
    value: 1.25
    vary: False
  k:
    value: 4.1
    vary: False
  a_w:
    value: -0.4
    vary: False
  a_k:
    value: -3.2
    vary: False
